name: test

on:
  push:
    branches: [ main ]
    tags: [ v* ]
  pull_request:

jobs:
  test:
    name: RSpec
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.6", "2.7", "3.0", "3.1"]
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - run: bundle exec rake
